export interface EasterEggMessage {
	text: string;
	color: number;
}

export const EASTER_EGG_MESSAGES: EasterEggMessage[] = [
	// ── Star Trek TNG ─────────────────────────────────────────────
	{ text: 'Tea. Earl Grey. Hot.', color: 0xffcc44 },
	{ text: 'Make it so.', color: 0xffcc44 },
	{ text: 'THERE ARE FOUR LIGHTS!', color: 0xffcc44 },
	{ text: 'Resistance is futile.', color: 0x44ff44 },
	{ text: 'Engage!', color: 0xffcc44 },
	{ text: 'The Prime Directive forbids...', color: 0xffcc44 },
	{ text: 'I am Locutus of Borg.', color: 0x44ff44 },
	{ text: 'Number One, you have the bridge.', color: 0xffcc44 },
	{ text: "It's a good day to die.", color: 0xff6644 },
	{ text: "I'm a doctor, not a doorstop!", color: 0x44aaff },
	{ text: 'The needs of the many\noutweigh the needs of the few.', color: 0x44aaff },
	{ text: 'Shut up, Wesley!', color: 0xff8844 },
	{ text: 'Computer, end program.', color: 0xffcc44 },
	{ text: 'Darmok and Jalad at Tanagra.', color: 0xffaa44 },
	{ text: "Q's watching.", color: 0xff44ff },
	{ text: "I'm fine.", color: 0xffcc44 },
	{ text: 'Today IS a good day to die!', color: 0xff4444 },
	{ text: 'Live long and prosper.', color: 0x44aaff },

	// ── Popular Games ─────────────────────────────────────────────
	{ text: "It's dangerous to go alone!", color: 0x44aaff },
	{ text: 'The cake is a lie.', color: 0xffffff },
	{ text: 'Do a barrel roll!', color: 0x44ff44 },
	{ text: 'Hey! Listen!', color: 0x88ffff },
	{ text: 'All your base are belong to us.', color: 0xff4444 },
	{ text: 'Would you kindly?', color: 0xccaa44 },
	{ text: 'War. War never changes.', color: 0xaa8844 },
	{ text: 'Stay a while and listen...', color: 0x8888ff },
	{ text: 'A winner is you!', color: 0xffff44 },
	{ text: 'The right man in the wrong place...', color: 0x4488cc },
	{ text: 'You must construct\nadditional pylons.', color: 0xffaa44 },
	{ text: 'Snake? Snake?! SNAAAAKE!', color: 0x88aa88 },
	{ text: 'Praise the sun! \\[T]/', color: 0xffdd44 },
	{ text: 'YOU DIED', color: 0xff2222 },
	{ text: 'Thank you Mario!\nBut our princess is\nin another castle.', color: 0xff4488 },
	{ text: "It's-a me!", color: 0xff4444 },
	{ text: 'The Enrichment Center\nreminds you that the\nweighted companion cube\ncannot speak.', color: 0xff88cc },
	{ text: 'A man chooses.\nA slave obeys.', color: 0xccaa44 },
	{ text: 'Hadouken!', color: 0x4488ff },
	{ text: 'Finish him.', color: 0xff4444 },
	{ text: "I used to be an\nadventurer like you...", color: 0xaaaaaa },
	{ text: 'Waka waka waka', color: 0xffff44 },
	{ text: "Boy, that's a nice\ntwo-headed monkey.", color: 0xaa8844 },
	{ text: "Look behind you!\nA three-headed monkey!", color: 0xaa8844 },
	{ text: 'How appropriate.\nYou fight like a cow.', color: 0xaa8844 },

	// ── Mighty Boosh ──────────────────────────────────────────────
	{ text: "I'm Old Gregg!", color: 0x44ffaa },
	{ text: "Ever drunk Bailey's from a shoe?", color: 0x44ffaa },
	{ text: "I'm the Moon!", color: 0xeeeeff },
	{ text: 'This is an outrage!', color: 0xff8844 },
	{ text: 'The Funk is here.', color: 0xff44ff },
	{ text: "I got a bad feeling about this\ncrimp...", color: 0x44ffaa },
	{ text: "I've got a mangina!", color: 0x44ffaa },
	{ text: "You know me.\nI'm the Hitcher.", color: 0x44aa44 },
	{ text: "Don't kill me.\nI've got so much to give!", color: 0xff8844 },
	{ text: "Elements of the past\nand the future\ncombining to make\nsomething not quite\nas good as either.", color: 0xff44ff },
	{ text: "Boosh! Boosh!\nStronger than a moose!", color: 0xff8844 },

	// ── Monty Python ──────────────────────────────────────────────
	{ text: "'Tis but a scratch!", color: 0xff4444 },
	{ text: 'We are the Knights who say Ni!', color: 0x44ff44 },
	{ text: 'Run away! Run away!', color: 0xffff44 },
	{ text: 'Nobody expects the\nSpanish Inquisition!', color: 0xff4444 },
	{ text: 'I got better.', color: 0x88ff88 },
	{ text: "It's just a flesh wound!", color: 0xff4444 },
	{ text: 'Bring me a shrubbery!', color: 0x44aa44 },
	{ text: 'Your mother was a hamster!', color: 0xffaa44 },
	{ text: "He's not dead, he's resting.", color: 0x8888ff },
	{ text: 'What is the airspeed velocity\nof an unladen swallow?', color: 0xffcc44 },
	{ text: "We are the knights who\nsay... Ekke Ekke Ptang!", color: 0x44ff44 },
	{ text: 'Strange women lying in ponds\ndistributing swords is no\nbasis for a system\nof government!', color: 0xffcc44 },
	{ text: 'And now for something\ncompletely different.', color: 0xffffff },
	{ text: "He's not the Messiah!\nHe's a very naughty boy!", color: 0xffaa44 },
	{ text: 'What... is your\nfavourite colour?', color: 0xffcc44 },
	{ text: 'Ni!', color: 0x44ff44 },

	// ── Loom ──────────────────────────────────────────────────────
	{ text: 'Ask me about Loom\u2122', color: 0x8844ff },
	{ text: 'Are you a pirate?', color: 0x8844ff },
	{ text: 'Draft of Opening detected.', color: 0xaa88ff },
	{ text: 'The pattern of the Loom shifts...', color: 0x8844ff },
	{ text: 'You are not of the Guild.', color: 0xaa88ff },
	{ text: 'The Third Shadow grows.', color: 0x6633aa },
	{ text: 'Transcendence awaits\nthe worthy weaver.', color: 0xaa88ff },

	// ── Doom ──────────────────────────────────────────────────────
	{ text: 'Rip and tear!', color: 0xff2222 },
	{ text: 'IDDQD', color: 0xffff44 },
	{ text: 'IDKFA', color: 0xffff44 },
	{ text: 'You found a secret!', color: 0xffaa44 },
	{ text: 'Groovy.', color: 0xff4444 },
	{ text: 'BFG Division', color: 0x44ff44 },
	{ text: 'IDSPISPOPD', color: 0xffff44 },
	{ text: 'Knee-deep in the dead.', color: 0xff2222 },
	{ text: "You can't just shoot a hole\ninto the surface of Mars.", color: 0xff8844 },
	{ text: 'Against all the evil that\nHell can conjure...', color: 0xff4444 },

	// ── Sci-Fi / Space ────────────────────────────────────────────
	{ text: "I can't let you do that, Dave.", color: 0xff4444 },
	{ text: 'Open the pod bay doors, HAL.', color: 0xff4444 },
	{ text: 'In space, no one\ncan hear you scream.', color: 0x88aacc },
	{ text: 'May the Force\nbe with you.', color: 0x44aaff },
	{ text: "I've seen things you people\nwouldn't believe...", color: 0x88aacc },
	{ text: 'So say we all.', color: 0xffcc44 },
	{ text: 'The spice must flow.', color: 0xffaa44 },
	{ text: "Don't panic.", color: 0x44ff88 },
	{ text: 'So long, and thanks\nfor all the fish.', color: 0x44aaff },
	{ text: '42', color: 0x44ff88 }
];
